# Generated by Django 4.0.5 on 2022-07-01 11:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tgid',
        ),
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя в Telegram'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Занято'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='lease_time',
            field=models.DateTimeField(blank=True, verbose_name='Дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='bot.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='measurer',
            field=models.BooleanField(default=False, verbose_name='Нужен ли замерщик'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='work_time',
            field=models.CharField(max_length=50, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
    ]
