# Generated by Django 4.0.5 on 2022-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_cell_options_remove_order_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='height',
            field=models.FloatField(default=34, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='number',
            field=models.IntegerField(default=223, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='temperature',
            field=models.CharField(default=32, max_length=20, verbose_name='Температура'),
            preserve_default=False,
        ),
    ]
